name: _fetch
on:
    workflow_call:
        outputs:
            deno_version:
                value: ${{jobs.job.outputs.deno_version}}
jobs:
    job:
        name: deno version
        runs-on: ubuntu-latest
        outputs:
            deno_version: ${{steps.step.outputs.deno_version}}
        steps:
            - id: step
              name: get deno latest version
              run: echo deno_version=$(curl -Ls https://api.github.com/repos/denoland/deno/releases/latest | yq '.tag_name') >> ${{github.output}}