name: _test
on:
    workflow_call:
        inputs:
            deno_version:
                type: string
                required: true
jobs:
    test:
        name: 'test: ${{matrix.distro}}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                distro:
                    - alpine
                    - distroless
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: install docker-qemu
              uses: docker/setup-qemu-action@v3
            - name: build image
              uses: docker/build-push-action@v5
              with:
                pull: true
                no-cache: true
                tags: ${{github.sha}}
                platforms: linux/amd64
                context: '{{defaultContext}}:./src'
                file: ${{matrix.distro}}.dockerfile
                build-args: DENO_VERSION=${{inputs.deno_version}}
            - name: test image
              run: docker run --rm --init ${{github.sha}} eval -p 'new Date()'