name: cron
on:
    schedule:
        - cron: 0 0 * * *
jobs:
    fetch:
        uses: ./.github/workflows/_fetch.yaml
    compare:
        name: compare version
        runs-on: ubuntu-latest
        outputs:
            deno_latest: ${{steps.step.outputs.value}}
        needs:
            - fetch
        steps:
            - id: step
              name: compare dockerhub tag and deno latest version
              run: echo value=$(curl -Ls https://registry.hub.docker.com/v2/repositories/dojyorin/deno/tags?page_size=100 | yq -p j '.results[].name' | grep -q ${{needs.fetch.outputs.deno_version}}; echo ${?}) >> ${{github.output}}
    test:
        if: ${{needs.compare.outputs.deno_latest == 1}}
        uses: ./.github/workflows/_test.yaml
        with:
            deno_version: ${{needs.fetch.outputs.deno_version}}
        needs:
            - fetch
            - compare
    push:
        uses: ./.github/workflows/_push.yaml
        secrets: inherit
        with:
            deno_version: ${{needs.fetch.outputs.deno_version}}
        needs:
            - fetch
            - compare
            - test