name: release
on:
    push:
        tags: v[0-9]+.[0-9]+.[0-9]+
jobs:
    release:
        name: 'release: ${{github.ref_name}}'
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: dispatch release
              uses: softprops/action-gh-release@v1
              with:
                generate_release_notes: true
    fetch:
        uses: ./.github/workflows/action_fetch.yaml
    test:
        uses: ./.github/workflows/action_test.yaml
        with:
            deno_v: ${{needs.fetch.outputs.deno_v}}
        needs:
            - fetch
    push:
        uses: ./.github/workflows/action_build.yaml
        with:
            deno_v: ${{needs.fetch.outputs.deno_v}}
        needs:
            - fetch
            - test