name: release
on:
    push:
        tags: v[0-9]+.[0-9]+.[0-9]+
jobs:
    release:
        name: 'release: ${{github.ref_name}}'
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: dispatch release
              uses: softprops/action-gh-release@v1
              with:
                generate_release_notes: true
    fetch:
        uses: ./.github/workflows/_fetch.yaml
    test:
        uses: ./.github/workflows/_test.yaml
        with:
            deno_version: ${{needs.fetch.outputs.deno_version}}
        needs:
            - fetch
    push:
        uses: ./.github/workflows/_push.yaml
        secrets: inherit
        with:
            deno_version: ${{needs.fetch.outputs.deno_version}}
        needs:
            - fetch
            - test