name: test
on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - .git*
            - '**.md'
    pull_request:
        branches:
            - master
        paths-ignore:
            - .git*
            - '**.md'
jobs:
    fetch:
        uses: ./.github/workflows/action_fetch.yaml
    test:
        uses: ./.github/workflows/action_test.yaml
        with:
            deno_v: ${{needs.fetch.outputs.deno_v}}
        needs:
            - fetch