name: test
on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - .git*
            - '**.md'
    pull_request:
        branches:
            - master
        paths-ignore:
            - .git*
            - '**.md'
jobs:
    test:
        name: 'test: ${{matrix.distro}}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                distro:
                    - alpine
                    - distroless
        env:
            tag_l: ${{github.repository_owner}}/deno:latest
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: install docker-qemu
              uses: docker/setup-qemu-action@v3
            - name: get original deno version
              run: echo DENO_VERSION=$(curl -Ls https://api.github.com/repos/denoland/deno/releases/latest | yq '.tag_name') >> ${{github.env}}
            - name: build image
              uses: docker/build-push-action@v5
              with:
                pull: true
                no-cache: true
                tags: ${{env.tag_l}}
                platforms: linux/amd64
                context: '{{defaultContext}}:./src'
                file: ${{matrix.distro}}.dockerfile
                build-args: DENO_VERSION=${{env.DENO_VERSION}}
            - name: test image
              run: docker run --init --rm ${{env.tag_l}} eval -p 'new Date()'
            - name: test image
              uses: addnab/docker-run-action@v3
              with:
                image: ${{env.tag_l}}
                shell: /usr/local/bin/deno
                run: eval -p 'new Date()'